{{/*
Expand the name of the chart.
*/}}
{{- define "mongodb.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "mongodb.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "mongodb.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "mongodb.labels" -}}
helm.sh/chart: {{ include "mongodb.chart" . }}
{{ include "mongodb.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/component: database
{{- end }}

{{/*
Selector labels
*/}}
{{- define "mongodb.selectorLabels" -}}
app.kubernetes.io/name: {{ include "mongodb.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Password secret name
*/}}
{{- define "mongodb.passwordSecretName" -}}
{{- printf "%s-password" (include "mongodb.fullname" .) }}
{{- end }}

{{/*
SCRAM credentials secret name (generated by operator)
*/}}
{{- define "mongodb.scramSecretName" -}}
{{- printf "%s-scram" (include "mongodb.fullname" .) }}
{{- end }}

{{/*
Connection string secret name (generated by operator)
The operator creates a secret named: {resource}-{auth-db}-{username}
See: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/users.md
*/}}
{{- define "mongodb.connectionSecretName" -}}
{{- printf "%s-%s-%s" (include "mongodb.fullname" .) "admin" (.Values.username | default "app") }}
{{- end }}

{{/*
Service name for MongoDB
*/}}
{{- define "mongodb.serviceName" -}}
{{- printf "%s-svc" (include "mongodb.fullname" .) }}
{{- end }}

{{/*
Environment variables for MongoDB connection
Use this template in your application deployment to inject database credentials:

  env:
    {{- include "mongodb.envVars" .Subcharts.mongodb | nindent 4 }}

This injects:
  - MONGODB_URI: Full connection string
*/}}
{{- define "mongodb.envVars" -}}
{{- if .Values.enabled }}
- name: MONGODB_URI
  valueFrom:
    secretKeyRef:
      name: {{ include "mongodb.connectionSecretName" . }}
      key: connectionString.standard
{{- end }}
{{- end }}

{{/*
Environment variables with custom prefix
*/}}
{{- define "mongodb.envVarsWithPrefix" -}}
{{- $prefix := .prefix | default "MONGO" }}
{{- $ctx := .context }}
{{- if $ctx.Values.enabled }}
- name: {{ $prefix }}_URI
  valueFrom:
    secretKeyRef:
      name: {{ include "mongodb.connectionSecretName" $ctx }}
      key: connectionString.standard
{{- end }}
{{- end }}
