name: 'Validate Config'
description: 'Parse and validate k8s-ee.yaml configuration file against JSON schema'

inputs:
  config-path:
    description: 'Path to k8s-ee.yaml configuration file'
    required: false
    default: 'k8s-ee.yaml'
  pr-number:
    description: 'PR number for derived values'
    required: true
  repository:
    description: 'GitHub repository (owner/repo)'
    required: true
  preview-domain:
    description: 'Base domain for preview URLs'
    required: false
    default: 'k8s-ee.genesluna.dev'

outputs:
  config-json:
    description: 'Full configuration as JSON with defaults applied'
    value: ${{ steps.parse.outputs.config-json }}
  project-id:
    description: 'Project ID from configuration'
    value: ${{ steps.parse.outputs.project-id }}
  namespace:
    description: 'Computed namespace (projectId-pr-number)'
    value: ${{ steps.parse.outputs.namespace }}
  preview-url:
    description: 'Full preview URL'
    value: ${{ steps.parse.outputs.preview-url }}
  app-port:
    description: 'Application port'
    value: ${{ steps.parse.outputs.app-port }}
  health-path:
    description: 'Health check path'
    value: ${{ steps.parse.outputs.health-path }}
  image-context:
    description: 'Docker build context'
    value: ${{ steps.parse.outputs.image-context }}
  image-dockerfile:
    description: 'Dockerfile path'
    value: ${{ steps.parse.outputs.image-dockerfile }}
  postgresql-enabled:
    description: 'PostgreSQL enabled flag'
    value: ${{ steps.parse.outputs.postgresql-enabled }}
  mongodb-enabled:
    description: 'MongoDB enabled flag'
    value: ${{ steps.parse.outputs.mongodb-enabled }}
  redis-enabled:
    description: 'Redis enabled flag'
    value: ${{ steps.parse.outputs.redis-enabled }}
  minio-enabled:
    description: 'MinIO enabled flag'
    value: ${{ steps.parse.outputs.minio-enabled }}
  mariadb-enabled:
    description: 'MariaDB enabled flag'
    value: ${{ steps.parse.outputs.mariadb-enabled }}
  postgresql-config:
    description: 'Full PostgreSQL configuration as JSON'
    value: ${{ steps.parse.outputs.postgresql-config }}
  mongodb-config:
    description: 'Full MongoDB configuration as JSON'
    value: ${{ steps.parse.outputs.mongodb-config }}
  redis-config:
    description: 'Full Redis configuration as JSON'
    value: ${{ steps.parse.outputs.redis-config }}
  minio-config:
    description: 'Full MinIO configuration as JSON'
    value: ${{ steps.parse.outputs.minio-config }}
  mariadb-config:
    description: 'Full MariaDB configuration as JSON'
    value: ${{ steps.parse.outputs.mariadb-config }}
  metrics-enabled:
    description: 'Metrics ServiceMonitor enabled flag'
    value: ${{ steps.parse.outputs.metrics-enabled }}
  metrics-config:
    description: 'Full metrics configuration as JSON'
    value: ${{ steps.parse.outputs.metrics-config }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
        REPOSITORY: ${{ inputs.repository }}
        CONFIG_PATH: ${{ inputs.config-path }}
        PREVIEW_DOMAIN: ${{ inputs.preview-domain }}
      run: |
        set -euo pipefail

        # Validate PR number is numeric
        if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
          echo "ERROR: pr-number must be numeric"
          echo "Received: '$PR_NUMBER'"
          exit 1
        fi

        # Validate repository format
        if ! [[ "$REPOSITORY" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
          echo "ERROR: repository must be in format 'owner/repo'"
          echo "Received: '$REPOSITORY'"
          exit 1
        fi

        # Validate config-path doesn't contain path traversal
        if [[ "$CONFIG_PATH" =~ \.\. ]] || [[ "$CONFIG_PATH" =~ ^/ ]]; then
          echo "ERROR: config-path cannot contain '..' or start with '/'"
          echo "Received: '$CONFIG_PATH'"
          exit 1
        fi

        # Validate preview-domain format
        if ! [[ "$PREVIEW_DOMAIN" =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]+[a-zA-Z0-9]$ ]]; then
          echo "ERROR: preview-domain must be a valid domain name"
          echo "Received: '$PREVIEW_DOMAIN'"
          exit 1
        fi

        echo "Input validation passed"

    - name: Validate organization access
      shell: bash
      env:
        REPOSITORY: ${{ inputs.repository }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        set -euo pipefail

        # Resolve config path relative to action directory
        CONFIG_FILE="${ACTION_PATH}/../config/allowed-orgs.json"

        if [ ! -f "$CONFIG_FILE" ]; then
          echo "WARNING: Allowed organizations config not found at: $CONFIG_FILE"
          echo "Proceeding without organization restriction (backwards compatibility)"
          exit 0
        fi

        # Validate JSON syntax
        if ! jq empty "$CONFIG_FILE" 2>/dev/null; then
          echo "ERROR: Invalid JSON in allowed-orgs.json"
          exit 1
        fi

        # Extract organization from repository (owner/repo -> owner)
        CALLING_ORG=$(echo "$REPOSITORY" | cut -d'/' -f1)
        CALLING_REPO="$REPOSITORY"

        echo "Checking access for organization: $CALLING_ORG"
        echo "Repository: $CALLING_REPO"

        # Parse config
        MODE=$(jq -r '.mode // "allowlist"' "$CONFIG_FILE")
        ORG_COUNT=$(jq '.organizations | length' "$CONFIG_FILE")
        REPO_COUNT=$(jq '.repositories // [] | length' "$CONFIG_FILE")

        echo "Access control mode: $MODE"
        echo "Allowed organizations: $ORG_COUNT"
        echo "Allowed repositories: $REPO_COUNT"

        if [ "$MODE" = "disabled" ]; then
          echo "Organization access control is disabled"
          exit 0
        fi

        # Warn if allowlist is empty (fail-safe: denies all)
        if [ "$MODE" = "allowlist" ] && [ "$ORG_COUNT" -eq 0 ] && [ "$REPO_COUNT" -eq 0 ]; then
          echo "WARNING: Allowlist is empty - all access will be denied"
        fi

        # Check if repository is explicitly listed (overrides org-level)
        # Case-insensitive comparison
        REPO_MATCH=$(jq -r --arg repo "$CALLING_REPO" \
          '(.repositories // []) | map(ascii_downcase) | index($repo | ascii_downcase) != null' \
          "$CONFIG_FILE")

        # Check if organization is listed (case-insensitive)
        ORG_MATCH=$(jq -r --arg org "$CALLING_ORG" \
          '(.organizations // []) | map(ascii_downcase) | index($org | ascii_downcase) != null' \
          "$CONFIG_FILE")

        # Determine access based on mode
        if [ "$MODE" = "allowlist" ]; then
          if [ "$REPO_MATCH" = "true" ] || [ "$ORG_MATCH" = "true" ]; then
            echo "Access granted: '$CALLING_ORG' is authorized"
            if [ "$REPO_MATCH" = "true" ]; then
              echo "  Match type: specific repository override"
            else
              echo "  Match type: organization allowlist"
            fi
            exit 0
          else
            echo ""
            echo "============================================================"
            echo "ERROR: Organization '$CALLING_ORG' is not authorized"
            echo "============================================================"
            echo ""
            echo "Repository '$CALLING_REPO' attempted to use k8s-ephemeral-environments"
            echo "but the organization is not in the allowed list."
            echo ""
            echo "To request access, please open an issue at:"
            echo "https://github.com/koder-cat/k8s-ephemeral-environments/issues"
            echo ""
            exit 1
          fi
        elif [ "$MODE" = "denylist" ]; then
          if [ "$REPO_MATCH" = "true" ] || [ "$ORG_MATCH" = "true" ]; then
            echo ""
            echo "============================================================"
            echo "ERROR: Organization '$CALLING_ORG' is blocked"
            echo "============================================================"
            echo ""
            echo "Repository '$CALLING_REPO' is not allowed to use this platform."
            echo ""
            exit 1
          else
            echo "Access granted: '$CALLING_ORG' is not in the denylist"
            exit 0
          fi
        else
          echo "ERROR: Unknown access control mode: $MODE"
          exit 1
        fi

    - name: Install tools
      shell: bash
      env:
        RUNNER_ARCH: ${{ runner.arch }}
      run: |
        set -euo pipefail

        # Determine architecture
        if [ "$RUNNER_ARCH" = "ARM64" ]; then
          ARCH="arm64"
          YQ_SHA256="a2cc6ca84dba8b156612df59dd8c2a8362f00aabceeb46d10d6e9c67da1199f6"
        else
          ARCH="amd64"
          YQ_SHA256="654fb44c8d4fb524ad3d271b636624a0c5ec8a6c95ede5d264c6f4763a3cfc73"
        fi

        # Install yq for YAML parsing (with checksum verification)
        if ! command -v yq &> /dev/null; then
          echo "Installing yq..."
          YQ_VERSION="v4.44.1"
          curl -fsSL --connect-timeout 10 --max-time 60 "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${ARCH}" -o /tmp/yq

          echo "Verifying yq checksum..."
          echo "${YQ_SHA256}  /tmp/yq" | sha256sum -c -

          chmod +x /tmp/yq
          sudo mv /tmp/yq /usr/local/bin/yq
          echo "yq installed: $(yq --version)"
        else
          echo "yq already installed: $(yq --version)"
        fi

        # Install ajv-cli for JSON Schema validation (pinned versions for reproducibility)
        if ! command -v ajv &> /dev/null; then
          echo "Installing ajv-cli..."
          npm install -g ajv-cli@5.0.0 ajv-formats@3.0.1
        else
          echo "ajv-cli already installed"
        fi

    - name: Check config file exists
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
      run: |
        set -euo pipefail

        # Verify file is within workspace (defense in depth)
        RESOLVED_PATH=$(realpath -m "$CONFIG_PATH" 2>/dev/null || echo "$CONFIG_PATH")
        WORKSPACE=$(realpath "$GITHUB_WORKSPACE")

        if [[ ! "$RESOLVED_PATH" =~ ^"$WORKSPACE" ]]; then
          echo "ERROR: config-path must be within the repository"
          exit 1
        fi

        if [ ! -f "$CONFIG_PATH" ]; then
          echo "ERROR: Configuration file not found: $CONFIG_PATH"
          echo ""
          echo "Please create a k8s-ee.yaml file in your repository root with at least:"
          echo ""
          echo "projectId: your-project-id"
          echo ""
          exit 1
        fi

        echo "Found configuration file: $CONFIG_PATH"

    - name: Parse and validate config
      id: parse
      shell: bash
      env:
        CONFIG_PATH: ${{ inputs.config-path }}
        PR_NUMBER: ${{ inputs.pr-number }}
        PREVIEW_DOMAIN: ${{ inputs.preview-domain }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        set -euo pipefail

        # Convert YAML to JSON
        echo "Parsing configuration..."
        CONFIG_JSON=$(yq -o=json "$CONFIG_PATH")

        # Write config to temp file for validation
        echo "$CONFIG_JSON" > /tmp/config.json

        # Validate against schema from action directory
        SCHEMA_PATH="${ACTION_PATH}/schema.json"
        echo "Validating configuration against schema..."
        if ! ajv validate -s "$SCHEMA_PATH" -d /tmp/config.json --all-errors -c ajv-formats 2>&1; then
          echo ""
          echo "ERROR: Configuration validation failed"
          echo "Please check your k8s-ee.yaml file against the schema requirements"
          exit 1
        fi
        echo "Configuration is valid"

        # Extract projectId (required field, already validated by schema)
        PROJECT_ID=$(echo "$CONFIG_JSON" | jq -r '.projectId')

        # Additional validation: projectId format (defense in depth)
        if ! [[ "$PROJECT_ID" =~ ^[a-z0-9]([a-z0-9-]{0,18}[a-z0-9])?$ ]]; then
          echo "ERROR: projectId must be lowercase alphanumeric with hyphens, 1-20 chars, start/end with alphanumeric"
          echo "Received: '$PROJECT_ID'"
          exit 1
        fi

        # Compute derived values
        NAMESPACE="${PROJECT_ID}-pr-${PR_NUMBER}"
        PREVIEW_URL="https://${NAMESPACE}.${PREVIEW_DOMAIN}"

        # Apply defaults and extract values
        APP_PORT=$(echo "$CONFIG_JSON" | jq -r '.app.port // 3000')
        HEALTH_PATH=$(echo "$CONFIG_JSON" | jq -r '.app.healthPath // "/health"')
        IMAGE_CONTEXT=$(echo "$CONFIG_JSON" | jq -r '.image.context // "."')
        IMAGE_DOCKERFILE=$(echo "$CONFIG_JSON" | jq -r '.image.dockerfile // "Dockerfile"')

        # Build final config with defaults applied
        FINAL_CONFIG=$(echo "$CONFIG_JSON" | jq --arg ns "$NAMESPACE" --arg url "$PREVIEW_URL" --arg pr "$PR_NUMBER" '
          . +
          {
            "_computed": {
              "namespace": $ns,
              "previewUrl": $url,
              "prNumber": ($pr | tonumber)
            }
          } |
          .app = (.app // {}) |
          .app.port = (.app.port // 3000) |
          .app.healthPath = (.app.healthPath // "/health") |
          .image = (.image // {}) |
          .image.context = (.image.context // ".") |
          .image.dockerfile = (.image.dockerfile // "Dockerfile") |
          .resources = (.resources // {}) |
          .resources.requests = (.resources.requests // {}) |
          .resources.requests.cpu = (.resources.requests.cpu // "50m") |
          .resources.requests.memory = (.resources.requests.memory // "128Mi") |
          .resources.limits = (.resources.limits // {}) |
          .resources.limits.cpu = (.resources.limits.cpu // "200m") |
          .resources.limits.memory = (.resources.limits.memory // "384Mi") |
          .env = (.env // {}) |
          .envFrom = (.envFrom // []) |
          .databases = (.databases // {}) |
          .databases.postgresql = (if .databases.postgresql == null then false else .databases.postgresql end) |
          .databases.mongodb = (if .databases.mongodb == null then false else .databases.mongodb end) |
          .databases.redis = (if .databases.redis == null then false else .databases.redis end) |
          .databases.minio = (if .databases.minio == null then false else .databases.minio end) |
          .databases.mariadb = (if .databases.mariadb == null then false else .databases.mariadb end) |
          .ingress = (.ingress // {}) |
          .ingress.enabled = (.ingress.enabled // true) |
          .metrics = (.metrics // {}) |
          .metrics.enabled = (.metrics.enabled // false)
        ')

        # Output results using heredoc for multiline JSON
        {
          echo "config-json<<EOF"
          echo "$FINAL_CONFIG"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

        echo "project-id=$PROJECT_ID" >> "$GITHUB_OUTPUT"
        echo "namespace=$NAMESPACE" >> "$GITHUB_OUTPUT"
        echo "preview-url=$PREVIEW_URL" >> "$GITHUB_OUTPUT"
        echo "app-port=$APP_PORT" >> "$GITHUB_OUTPUT"
        echo "health-path=$HEALTH_PATH" >> "$GITHUB_OUTPUT"
        echo "image-context=$IMAGE_CONTEXT" >> "$GITHUB_OUTPUT"
        echo "image-dockerfile=$IMAGE_DOCKERFILE" >> "$GITHUB_OUTPUT"

        # Extract database configuration flags (handles both boolean and object forms)
        # Object form defaults to enabled unless explicitly disabled (enabled: false)
        echo "postgresql-enabled=$(echo "$FINAL_CONFIG" | jq -r 'if .databases.postgresql == true then "true" elif .databases.postgresql == false then "false" elif (.databases.postgresql | type) == "object" then (if .databases.postgresql.enabled == false then "false" else "true" end) else "false" end')" >> "$GITHUB_OUTPUT"
        echo "mongodb-enabled=$(echo "$FINAL_CONFIG" | jq -r 'if .databases.mongodb == true then "true" elif .databases.mongodb == false then "false" elif (.databases.mongodb | type) == "object" then (if .databases.mongodb.enabled == false then "false" else "true" end) else "false" end')" >> "$GITHUB_OUTPUT"
        echo "redis-enabled=$(echo "$FINAL_CONFIG" | jq -r 'if .databases.redis == true then "true" elif .databases.redis == false then "false" elif (.databases.redis | type) == "object" then (if .databases.redis.enabled == false then "false" else "true" end) else "false" end')" >> "$GITHUB_OUTPUT"
        echo "minio-enabled=$(echo "$FINAL_CONFIG" | jq -r 'if .databases.minio == true then "true" elif .databases.minio == false then "false" elif (.databases.minio | type) == "object" then (if .databases.minio.enabled == false then "false" else "true" end) else "false" end')" >> "$GITHUB_OUTPUT"
        echo "mariadb-enabled=$(echo "$FINAL_CONFIG" | jq -r 'if .databases.mariadb == true then "true" elif .databases.mariadb == false then "false" elif (.databases.mariadb | type) == "object" then (if .databases.mariadb.enabled == false then "false" else "true" end) else "false" end')" >> "$GITHUB_OUTPUT"

        # Extract full database configuration as JSON (for passing additional options like bootstrap SQL)
        # Boolean true becomes {"enabled": true}, object form passes through, false/null becomes {"enabled": false}
        {
          echo "postgresql-config<<EOF"
          echo "$FINAL_CONFIG" | jq -c 'if .databases.postgresql == true then {"enabled": true} elif (.databases.postgresql | type) == "object" then .databases.postgresql + {"enabled": (if .databases.postgresql.enabled == false then false else true end)} else {"enabled": false} end'
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
        {
          echo "mongodb-config<<EOF"
          echo "$FINAL_CONFIG" | jq -c 'if .databases.mongodb == true then {"enabled": true} elif (.databases.mongodb | type) == "object" then .databases.mongodb + {"enabled": (if .databases.mongodb.enabled == false then false else true end)} else {"enabled": false} end'
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
        {
          echo "redis-config<<EOF"
          echo "$FINAL_CONFIG" | jq -c 'if .databases.redis == true then {"enabled": true} elif (.databases.redis | type) == "object" then .databases.redis + {"enabled": (if .databases.redis.enabled == false then false else true end)} else {"enabled": false} end'
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
        {
          echo "minio-config<<EOF"
          echo "$FINAL_CONFIG" | jq -c 'if .databases.minio == true then {"enabled": true} elif (.databases.minio | type) == "object" then .databases.minio + {"enabled": (if .databases.minio.enabled == false then false else true end)} else {"enabled": false} end'
          echo "EOF"
        } >> "$GITHUB_OUTPUT"
        {
          echo "mariadb-config<<EOF"
          echo "$FINAL_CONFIG" | jq -c 'if .databases.mariadb == true then {"enabled": true} elif (.databases.mariadb | type) == "object" then .databases.mariadb + {"enabled": (if .databases.mariadb.enabled == false then false else true end)} else {"enabled": false} end'
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

        # Extract metrics configuration
        echo "metrics-enabled=$(echo "$FINAL_CONFIG" | jq -r '.metrics.enabled // false')" >> "$GITHUB_OUTPUT"
        {
          echo "metrics-config<<EOF"
          echo "$FINAL_CONFIG" | jq -c '.metrics // {"enabled": false}'
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

        echo ""
        echo "=== Configuration Summary ==="
        echo "Project ID: $PROJECT_ID"
        echo "Namespace: $NAMESPACE"
        echo "Preview URL: $PREVIEW_URL"
        echo "App Port: $APP_PORT"
        echo "Health Path: $HEALTH_PATH"
        echo "Image Context: $IMAGE_CONTEXT"
        echo "Dockerfile: $IMAGE_DOCKERFILE"
        echo "Metrics Enabled: $(echo "$FINAL_CONFIG" | jq -r '.metrics.enabled // false')"
