name: 'Build Image'
description: 'Build ARM64 container image, push to GHCR, run Trivy scan, and generate SBOM'

inputs:
  context:
    description: 'Docker build context path'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile relative to context'
    required: false
    default: 'Dockerfile'
  image-name:
    description: 'Image name without registry (e.g., org/app)'
    required: true
  pr-number:
    description: 'PR number for tagging'
    required: true
  commit-sha:
    description: 'Full commit SHA for tagging'
    required: true
  registry:
    description: 'Container registry'
    required: false
    default: 'ghcr.io'
  platforms:
    description: 'Target platforms (comma-separated)'
    required: false
    default: 'linux/arm64'
  trivy-severity:
    description: 'Trivy severity levels to report'
    required: false
    default: 'CRITICAL,HIGH'
  github-token:
    description: 'GitHub token for registry authentication (packages:write) and SARIF upload (security-events:write)'
    required: true

outputs:
  image-tag:
    description: 'Short image tag (commit SHA)'
    value: ${{ steps.meta.outputs.version }}
  image-digest:
    description: 'Image digest for immutable reference'
    value: ${{ steps.build.outputs.digest }}
  image-ref:
    description: 'Full image reference with digest'
    value: ${{ steps.image-ref.outputs.image-ref }}
  trivy-sarif:
    description: 'Path to Trivy SARIF results file'
    value: ${{ steps.trivy-output.outputs.sarif-file }}
  sbom-file:
    description: 'Path to SBOM file'
    value: ${{ steps.sbom-output.outputs.sbom-file }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      env:
        CONTEXT: ${{ inputs.context }}
        DOCKERFILE: ${{ inputs.dockerfile }}
        IMAGE_NAME: ${{ inputs.image-name }}
        PR_NUMBER: ${{ inputs.pr-number }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        REGISTRY: ${{ inputs.registry }}
      run: |
        set -euo pipefail

        # Validate context path (no path traversal or absolute paths)
        if [[ "$CONTEXT" =~ \.\. ]]; then
          echo "ERROR: context path cannot contain '..'"
          echo "Received: '$CONTEXT'"
          exit 1
        fi
        if [[ "$CONTEXT" =~ ^/ ]]; then
          echo "ERROR: context path cannot be absolute"
          echo "Received: '$CONTEXT'"
          exit 1
        fi

        # Validate dockerfile path (no path traversal or absolute paths)
        if [[ "$DOCKERFILE" =~ \.\. ]]; then
          echo "ERROR: dockerfile path cannot contain '..'"
          echo "Received: '$DOCKERFILE'"
          exit 1
        fi
        if [[ "$DOCKERFILE" =~ ^/ ]]; then
          echo "ERROR: dockerfile path cannot be absolute"
          echo "Received: '$DOCKERFILE'"
          exit 1
        fi

        # Validate PR number is numeric
        if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
          echo "ERROR: pr-number must be numeric"
          echo "Received: '$PR_NUMBER'"
          exit 1
        fi

        # Validate commit SHA format
        if ! [[ "$COMMIT_SHA" =~ ^[a-f0-9]{40}$ ]]; then
          echo "ERROR: commit-sha must be a 40-character hex string"
          echo "Received: '$COMMIT_SHA'"
          exit 1
        fi

        # Validate image name format
        if ! [[ "$IMAGE_NAME" =~ ^[a-z0-9._-]+/[a-z0-9._-]+(/[a-z0-9._-]+)?$ ]]; then
          echo "ERROR: image-name must be in format 'owner/repo' or 'owner/repo/app'"
          echo "Received: '$IMAGE_NAME'"
          exit 1
        fi

        # Validate registry format
        if ! [[ "$REGISTRY" =~ ^[a-z0-9.-]+$ ]]; then
          echo "ERROR: registry must be a valid hostname"
          echo "Received: '$REGISTRY'"
          exit 1
        fi

        echo "Input validation passed"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Log in to registry
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: |
          type=sha,prefix=,format=short
          type=raw,value=pr-${{ inputs.pr-number }}

    - name: Build and push
      id: build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set image reference output
      id: image-ref
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        IMAGE_NAME: ${{ inputs.image-name }}
        DIGEST: ${{ steps.build.outputs.digest }}
      run: |
        echo "image-ref=${REGISTRY}/${IMAGE_NAME}@${DIGEST}" >> "$GITHUB_OUTPUT"

    - name: Make package public
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        IMAGE_NAME: ${{ inputs.image-name }}
      run: |
        set -euo pipefail

        # Extract owner and package name from image-name (e.g., koder-cat/k8s-ephemeral-environments/k8s-ee)
        OWNER="${IMAGE_NAME%%/*}"
        PACKAGE_NAME="${IMAGE_NAME#*/}"  # Remove owner prefix
        PACKAGE_NAME_ENCODED=$(echo "$PACKAGE_NAME" | sed 's|/|%2F|g')

        echo "Setting package visibility to public..."
        echo "  Owner: $OWNER"
        echo "  Package: $PACKAGE_NAME"

        # Try org endpoint first, fall back to user endpoint
        if gh api "/orgs/${OWNER}/packages/container/${PACKAGE_NAME_ENCODED}" --silent 2>/dev/null; then
          gh api --method PATCH "/orgs/${OWNER}/packages/container/${PACKAGE_NAME_ENCODED}" \
            -f visibility=public || echo "Warning: Could not set package visibility (may already be public)"
        else
          gh api --method PATCH "/user/packages/container/${PACKAGE_NAME_ENCODED}" \
            -f visibility=public || echo "Warning: Could not set package visibility (may already be public)"
        fi

        echo "Package visibility set to public"

    - name: Run Trivy vulnerability scanner
      id: trivy
      uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # v0.28.0
      env:
        TRIVY_PLATFORM: ${{ inputs.platforms }}
      with:
        image-ref: ${{ inputs.registry }}/${{ inputs.image-name }}@${{ steps.build.outputs.digest }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: ${{ inputs.trivy-severity }}
        exit-code: '0'
        ignore-unfixed: true

    - name: Set Trivy output
      id: trivy-output
      shell: bash
      run: |
        echo "sarif-file=trivy-results.sarif" >> "$GITHUB_OUTPUT"

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Upload Trivy scan results as artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: trivy-scan-results
        path: trivy-results.sarif
        retention-days: 30

    - name: Generate SBOM
      id: sbom
      uses: anchore/sbom-action@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0 # v0.18.0
      env:
        SYFT_PLATFORM: ${{ inputs.platforms }}
      with:
        image: ${{ inputs.registry }}/${{ inputs.image-name }}@${{ steps.build.outputs.digest }}
        format: spdx-json
        output-file: sbom-${{ inputs.pr-number }}.spdx.json
        artifact-name: sbom-pr-${{ inputs.pr-number }}
        upload-artifact: true
        upload-artifact-retention: 30

    - name: Set SBOM output
      id: sbom-output
      shell: bash
      env:
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        echo "sbom-file=sbom-${PR_NUMBER}.spdx.json" >> "$GITHUB_OUTPUT"

    - name: Build summary
      if: always()
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        IMAGE_NAME: ${{ inputs.image-name }}
        IMAGE_TAG: ${{ steps.meta.outputs.version }}
        IMAGE_DIGEST: ${{ steps.build.outputs.digest }}
        PLATFORMS: ${{ inputs.platforms }}
      run: |
        echo "=== Build Summary ==="
        echo "Image: ${REGISTRY}/${IMAGE_NAME}"
        echo "Tag: ${IMAGE_TAG}"
        echo "Digest: ${IMAGE_DIGEST}"
        echo "Platform: ${PLATFORMS}"
        echo "Trivy scan: trivy-results.sarif"
        echo "SBOM: sbom-${{ inputs.pr-number }}.spdx.json"
