#!/usr/bin/env bash
#
# Generate ConfigMaps from Python script source files.
# This ensures the ConfigMaps stay in sync with the source scripts.
#
# Usage: ./scripts/generate-configmaps.sh
#
# Scripts are the source of truth; ConfigMaps are generated artifacts.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Color output helpers
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Generate a ConfigMap YAML from a script file
# Args: $1 = script path, $2 = configmap name, $3 = namespace, $4 = output path, $5 = app name
generate_configmap() {
    local script_path="$1"
    local configmap_name="$2"
    local namespace="$3"
    local output_path="$4"
    local app_name="$5"

    local script_filename
    script_filename=$(basename "$script_path")

    log_info "Generating $output_path from $script_path"

    # Create the ConfigMap YAML
    cat > "$output_path" << EOF
# AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
# Source: scripts/${script_filename}
# Generated by: scripts/generate-configmaps.sh
#
# To update this ConfigMap, edit the source script and run:
#   ./scripts/generate-configmaps.sh
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${configmap_name}
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: ${app_name}
    app.kubernetes.io/component: script
data:
  ${script_filename}: |
EOF

    # Append the script content with proper YAML indentation (4 spaces)
    sed 's/^/    /' "$script_path" >> "$output_path"

    log_info "Generated $output_path"
}

# Main
main() {
    log_info "Generating ConfigMaps from script sources..."

    # Cleanup job ConfigMap
    generate_configmap \
        "$REPO_ROOT/scripts/cleanup-orphaned-namespaces.py" \
        "cleanup-script" \
        "platform" \
        "$REPO_ROOT/k8s/platform/cleanup-job/cleanup-configmap.yaml" \
        "cleanup-job"

    # Preserve expiry ConfigMap
    generate_configmap \
        "$REPO_ROOT/scripts/preserve-expiry.py" \
        "preserve-expiry-script" \
        "platform" \
        "$REPO_ROOT/k8s/platform/preserve-expiry/preserve-expiry-configmap.yaml" \
        "preserve-expiry"

    log_info "All ConfigMaps generated successfully"
}

main "$@"
